# Run a test server on port 8000.
run:
	../manage.py runserver 0.0.0.0:8000

# Clean up intermediate files.
# May be easier with "git clean".
clean:
	find . -name \*.pyc -type f -delete
	find . -name __pycache__ -type d -delete